---
apiVersion: v1
kind: Service
metadata:
  name: kibana
spec:
  ports:
  - port: 5601
    protocol: TCP
    targetPort: 5601
  selector:
    app: kibana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  labels:
    "kubernetes.io/cluster-service": "true"
    "addonmanager.kubernetes.io/mode": "Reconcile"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
      name: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:6.2.4
        ports:
        - containerPort: 5601
          protocol: TCP
        env:
        - name: ELASTICSEARCH_URL
          value: http://elasticsearch.default.svc.cluster.local:9200
        resources:
          requests:
            cpu: 0.2
            memory: 1024
        readinessProbe:
          httpGet:
            path: /
            port: 5601
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 15