namespace: vampio
database-type: mysql
database-name: vamp-${namespace}
database-url: jdbc:mysql://localhost:3306/vamp-${namespace}
database-user: root
database-table: ${namespace}
database-password: secret
key-value-store-url: http://localhost:8200
key-value-store-token: vamp
key-value-store-base-path: /secret/vamp/${namespace}
key-value-store-type: vault
release-policies-path: /workflows/release/policies/