apiVersion: v1
kind: Service
metadata:
  name: nats-streaming
spec:
  ports:
  - port: 4222
    protocol: TCP
    targetPort: 4222
  selector:
    app: nats-streaming
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-streaming
spec:
  selector:
    matchLabels:
      app: nats-streaming
      version: 0.12.0
  replicas: 1
  template:
    metadata:
      labels:
        app: nats-streaming
        version: 0.12.0
      name: nats-streaming
    spec:
      containers:
      - name: nats-streaming
        image: nats-streaming:0.12.0
        args: ["-p", "4222", "-m", "8222", "--max_channels", "200"]
        ports:
        - name: client
          containerPort: 4222
          protocol: TCP
        - name: monitoring
          containerPort: 8222
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: monitoring
          initialDelaySeconds: 5
          periodSeconds: 15