kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vamp:quantification:health-reader
rules:
- apiGroups: ["","apps"]
  resources: ["deployments","pods"]
  verbs: ["get","list"]

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: vamp-quantification
  namespace: default

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vamp:quantification:health-reader
subjects:
- kind: ServiceAccount
  name: vamp-quantification
roleRef:
  kind: Role
  name: vamp:quantification:health-reader
  apiGroup: rbac.authorization.k8s.io