apiVersion: apps/v1
kind: Deployment
metadata:
  name: particles-v1.0.1
  namespace: vampio-organization-environment
spec:
  selector:
    matchLabels:
      app: particles
  replicas: 1
  template:
    metadata:
      labels:
        app: particles
        version: 1.0.1
    spec:
      containers:
      - name: particles
        image: magneticio/particles
        imagePullPolicy: Always
        args:
          - "--color=#FF0000"
          - "--appVersion=v1.0.1"
          - "--showStats"
        ports:
        - containerPort: 5000
          protocol: TCP
        resources:
          requests:
            cpu: 0.1
            memory: 256
