apiVersion: apps/v1
kind: Deployment
metadata:
  name: particles-v1.1.0
  namespace: vampio-organization-environment
spec:
  selector:
    matchLabels:
      app: particles
  replicas: 1
  template:
    metadata:
      labels:
        app: particles
        version: 1.1.0
    spec:
      containers:
      - name: particles
        image: magneticio/particles
        imagePullPolicy: Always
        args:
          - "--appVersion=v1.1.0"
          - "--color=#0000FF"
          - "--shape=rectangle"
          - "--errorRate=2"
          - "--showStats"
        ports:
        - containerPort: 5000
          protocol: TCP
        resources:
          requests:
            cpu: 0.1
            memory: 256
